<?php

/**
 * @file
 * Hologram module main file.
 *
 */

function hologram_gallery_menu(){
  $items['admin/config/hologram-gallery'] = array(
  'title' => 'Hologram Gallery',
  'description' => 'Configuration of Hologram Gallery',
  'page callback' => 'hologram_gallery_admin',
  'access arguments' => array('administer hologram'),
  'type' => MENU_NORMAL_ITEM,
  'file' => 'hologram_gallery.admin.inc'
}
